import "./style/banner.scss";
import "destyle.css/destyle.css";
// import 'selectize/dist/css/selectize.css';
import 'nouislider/dist/nouislider.css';
import 'tippy.js/dist/tippy.css';
// import 'swiper/swiper-bundle.css';

import "./style/blocks/btn.scss";
import "./style/blocks/checkbox.scss";
import "./style/blocks/input.scss";
import "./style/blocks/select.scss";
import "./style/blocks/slider.scss";
import "./style/blocks/wpcf7.scss";
import "./style/fonts.scss";
import "./style/common.scss";
import "./style/typography.scss";

import './modules/photoswipe/photoswipe.scss';
import './modules/photoswipe/default-skin.scss';

import './modules/popup/popup.scss';
import './modules/popup/thank.scss';
import './modules/header/header.scss';
import './modules/counter/counter.scss';
import './modules/about/about.scss';
import './modules/system/system.scss';
import './modules/issues/issues.scss';
import './modules/operations/operations.scss';
import './modules/wait/wait.scss';
import './modules/examples/examples.scss';
import './modules/ya/ya.scss';
import './modules/video/video.scss';
import './modules/testimonials/testimonials.scss';
import './modules/record/record.scss';
import './modules/form/form.scss';
import './modules/support/support.scss';
import './modules/price/price.scss';
import './modules/team/team.scss';
import './modules/restore/restore.scss';
import './modules/footer/footer.scss';
import './modules/team-info/team-info.scss';
